spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/crypto-automation'
    username: root
    password: greenday32

  sql:
    init:
      mode: never # ??
