name: 업비트 코인 시세 데이터 조회

on:
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Download Gradle Wrapper
        run: ./gradlew wrapper --gradle-version 8.11.1
      - name: Verify Gradle Wrapper
        run: ./gradlew --version
      - name: Build with Gradle
        run: ./gradlew clean :build -x test
      - name: Run batch
        run: java -jar -Dspring.batch.job.name=tickerSlackJob -Dspring.profiles.active=github ./build/libs/Cryptocurrency-0.0.1-SNAPSHOT.jar market=KRW-BTC


